### ISSUE TITLE
BoP Transparency on Certain Blockks

### ISSUE THREAD

**Issue by Darkosto** [Soartex-Modded/Modded-1.10.x#10]
Heya @Shoeboxam 

I found some of these: 

https://sx.artdude.uk/hotlink-ok/darkosto/raL2-f3819-1479317051.jpg

So far, it looks to be Loamy and Sandy grass blocks.

Thanks! :D

**Comment by Shoeboxam** [comment]
Thanks for the heads up. I'll be able to take a stab at cleaning up BoP this weekend. I have a bit more of an experimental fix in mind ;)

**Comment by Darkosto** [comment]
No worries! I've been testing out and checking the new textures today. They look great so far!

**Comment by Darkosto** [comment]
Fixed. Thanks!
