### ISSUE TITLE
Where can I find this background?

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Soartex-Modded/Modded-1.10.x#20]
If you have,please give me
![uc 20161210152926](https://cloud.githubusercontent.com/assets/20567492/21071968/91ba1500-beed-11e6-98e0-eeab31d2fd16.png)

**Comment by Shoeboxam** [comment]
I have all the textures for the wood gui here:
https://github.com/Soartex-Modded/Templates/blob/master/gui/Wood/
The scroll is called paper_backing.png. When you resize it, don't use interpolation!

I just added it- I didn't realize that texture was not up on the repo. Thanks for bringing this up.
