### ISSUE TITLE
Applied Energistics 2 Dense Cable textures are glitched (half transparent)

### ISSUE THREAD

**Issue by mickdekkers** [Soartex-Modded/Modded-1.10.x#27]
The textures for AE2 Dense Cables seem to be glitched, but the other cables appear fine.
Here's a screenshot:
![http://puu.sh/t52z2/28d6d3e509.png](http://puu.sh/t52z2/28d6d3e509.png)

Build 12/29/2016

Edit: The textures seem to have different layouts.

Compare the stock version:
<img src="https://rawgit.com/AppliedEnergistics/Applied-Energistics-2/1.10/src/main/resources/assets/appliedenergistics2/textures/parts/cable/dense/magenta.png" alt="Stock version" style="width: 100px; image-rendering: pixelated;">

To the Soartex version:
<img src="https://rawgit.com/Soartex-Modded/Modded-1.10.x/master/Applied_Energistics_2/assets/appliedenergistics2/textures/parts/cable/dense/magenta.png" alt="Soartex version" style="width: 100px; image-rendering: pixelated;">

**Comment by Shoeboxam** [comment]
Thanks for the report. Sorry about the long turnaround, we get to these issues as soon as possible, but it does take time.

**Comment by mickdekkers** [comment]
No worries, thanks for the fix!
