### ISSUE TITLE
JEI Background Sometimes Causes Text Too Difficult To Read On Occasion

### ISSUE THREAD

**Issue by Darkosto** [Soartex-Modded/Modded-1.10.x#29]
https://sx.artdude.uk/hotlink-ok/darkosto/wAdf-c6511-1483655577.png

**Comment by artdude543** [comment]
@zISKo666 As you made the changes to JEI could you take a look into this one please? 😄

**Comment by zISKo666** [comment]
Sure I'll do :)

**Comment by zISKo666** [comment]
please try this https://github.com/Soartex-Modded/Modded-1.10.x/commit/f0479759b2e4fb0271981c55b2b517e11a3a01b7
