### ISSUE TITLE
[Missing] Some textures.

### ISSUE THREAD

**Issue by bontavi** [Soartex-Modded/Modded-1.10.x#31]
Client log - http://pastebin.com/eGJe3Nvx .
For some reason certain block are missing some textures. I have found this in client logs, when i'm loading it.

**Comment by Shoeboxam** [comment]
That's interesting- do the same errors appear when you are not using a resource pack?

**Comment by bontavi** [comment]
I will test it.

**Comment by bontavi** [comment]
Okey, it seems mods or minecraft issue. :)

**Comment by Shoeboxam** [comment]
No worries! Be sure to open an issue if you run into any other problems!
