### ISSUE TITLE
[Request] Industrial Craft 2 MC 1.10.2

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [Soartex-Modded/Modded-1.10.x#4]
http://www.industrial-craft.net/

**Comment by UnPure** [comment]
I ported all existing textures from 1.7.10 to 1.10.2 and added a few new ones.

https://github.com/Soartex-Modded/Modded-1.10.x/commit/b9d1684a3ad7ef1ad207992e60b785d18ec7521e
