### ISSUE TITLE
Weird Issues (infested leaves) and Specter

### ISSUE THREAD

**Issue by zzyzzyzzx** [Soartex-Modded/Modded-1.10.x#45]
not sure if this is the right place, or what, im using invicitus (not sure if this is for fanver)

1) infested leaves do not render
![transparent leaves](http://i68.tinypic.com/2w30zrl.png)

2) specter arrows seem to turn the screen black which makes the game unplayable
![specter](http://i65.tinypic.com/a11dzd.png)

**Comment by Shoeboxam** [comment]
Images are missing, and I don't have any context for where infested leaves or specter arrows come from. Closing. Please reopen if this is still an issue and you have more info!
