### ISSUE TITLE
Tinkers' Textures?

### ISSUE THREAD

**Issue by Darkosto** [Soartex-Modded/Modded-1.10.x#46]
What happened to all of the textures I did for the TCon item parts/tools?

**Comment by ScottKillen** [comment]
Please be more specific. Github doesn't show any activity for you with regard to that.

**Comment by artdude543** [comment]
I can vouch for this. They somehow have been lost somewhere. I uploaded them ages ago but I can't find a commit of someone removing them. I could backtrace to my commit of adding them and re-add em, but I made a load of edits also which would be lost. So it's a loss either way at the moment.

**Comment by Darkosto** [comment]
I went through and finished up a majority of the tool parts today for 1.11.2, they are in the shared dropbox folder along with a few other mods I've ported.

**Comment by artdude543** [comment]
Okay, thanks! Will check them out after work.

**Comment by Shoeboxam** [comment]
My texture porting algorithm shows +546 files to Tinker's pulled from other mod support versions. I assume this includes your textures. Please reopen if there are still missing textures.
https://github.com/Soartex-Modded/Modded-1.10.x/pull/59
