### ISSUE TITLE
XNet Texture -> Missing channel information in Controller Gui

### ISSUE THREAD

**Issue by Morbidcactus** [Soartex-Modded/Modded-1.10.x#47]
I've updated both Invictus and Fanver, both are missing channel info inside of the controller gui. I can create and edit channels, however I have no idea what is assigned to what channel. I can provide additional info if required 

![2017-06-18_12 34 52](https://user-images.githubusercontent.com/29522189/27262387-b0933e68-5423-11e7-91fd-daa588e61414.png)
GUI /w Faithful

![2017-06-18_12 35 57](https://user-images.githubusercontent.com/29522189/27262388-b09404ba-5423-11e7-8817-2f67af668779.png)
GUI /w Fanver

![2017-06-18_12 40 42](https://user-images.githubusercontent.com/29522189/27262389-b0953420-5423-11e7-83e7-de1b529b3a1b.png)
GUI /w Invictus

**Comment by mgdgfbhevdyeh** [comment]
I don't make that.

**Comment by mgdgfbhevdyeh** [comment]
I not make controller.png.
https://github.com/Soartex-Modded/Modded-1.10.x/blob/master/XNet/assets/xnet/textures/gui/~untextured.txt#L2

Edit:I think it might be guielements.png because I was copying RFTOOLS directly
