### ISSUE TITLE
Download links on soartex.net are dead

### ISSUE THREAD

**Issue by dragonshardz** [Soartex-Modded/Modded-1.10.x#49]
N/T. All lead to a 404 error.

**Comment by mgdgfbhevdyeh** [comment]
are you really?
it's work well

**Comment by dragonshardz** [comment]
When I posted this issue, they were all dead. They're working now.

**Comment by Shoeboxam** [comment]
Yeah, I didn't see any issues. Curse probably had a little downtime. Thanks for the comment, regardless!
