### ISSUE TITLE
Immersive Engineering Ore textures file name mismatch

### ISSUE THREAD

**Issue by unforbidable** [Soartex-Modded/Modded-1.10.x#51]
Some textures file names for Immersive Engineering are incorrect. As the result, the default textures are used. For example, `ore_Copper.png` should be `ore_copper.png`.  Note the case, and note that the case only matters when the resource pack is zipped. When extract into a folder the case does not matter and the new textures files are loaded. File names of textures of all ores are incorrect.

https://github.com/BluSunrize/ImmersiveEngineering/tree/master/src/main/resources/assets/immersiveengineering/textures/blocks

**Comment by mgdgfbhevdyeh** [comment]
The file name in Minecraft 1.11 must be lowercase
