### ISSUE TITLE
Is it possible to move textures from Modded-1.7 to Modded-1.10?

### ISSUE THREAD

**Issue by z0mbat** [Soartex-Modded/Modded-1.10.x#54]
1.7 is more complete than 1.10. I really miss Thermal Foundation in the 1.10 pack. I tried moving the folder from 1.7 to the 1.10 zip, but the textures are not showing up. 

Is it possible to do this? If not - what is preventing from working?

**Comment by ScottKillen** [comment]
It might not work if the 1.10 version of them mod uses textures with different names or paths than the 1.10 version of the mod.

mod ,jar files are simply renamed .zip files. If you open a ,jar file with something that reads zip files, you can figure out the texture paths and names.
